routes/admin.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PostsController;
use App\Http\Controllers\Admin\UsersController;
use Illuminate\Support\Facades\Route;

Route::get('', DashboardController::class)->name('dashboard');

Route::prefix('users')
    ->name('users.')
    ->group(function () {
        Route::get('', [UsersController::class, 'index'])->name('index');
    });

Route::prefix('posts')
    ->name('posts.')
    ->group(function () {
        Route::get('', [PostsController::class, 'index'])->name('index');
        Route::get('create', [PostsController::class, 'create'])->name('create');
        Route::post('', [PostsController::class, 'store'])->name('store');
        Route::get('{post}/edit', [PostsController::class, 'edit'])->name('edit');
        Route::put('{post}', [PostsController::class, 'update'])->name('update');
        Route::get('{post}/delete', [PostsController::class, 'destroy'])->name('destroy');
    });

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\PostsController;
use App\Http\Controllers\RegisterController;
use App\Http\Middleware\RedirectIfAuthenticated;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('', HomeController::class)->name('home');

Route::middleware(RedirectIfAuthenticated::class)
    ->group(function () {
        Route::match(['get', 'post'], 'login', LoginController::class)->name('login');
        Route::match(['get', 'post'], 'register', RegisterController::class)->name('register');
    });

Route::get('logout', [LoginController::class, 'logout'])->name('logout');

Route::prefix('posts')->name('posts.')->group(function () {
    Route::post('{post}/vote', [PostsController::class, 'vote'])->name('vote')->middleware('auth');
    Route::get('{post}', [PostsController::class, 'show'])->name('show');
});

resources/views/home.blade.php
@extends('layout')

@section('styles')
    <link rel="stylesheet" href="{{asset('css/blog.css')}}"/>
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            @foreach($posts as $post)
                <div class="blog-post">
                    <h2 class="blog-post-title">
                        <a href="{{route('posts.show',['post'=>$post->id])}}">{{$post->title}}</a>
                    </h2>
                    <p class="blog-post-meta">{{$post->createdAtWithFormat('M d, Y')}} by {{$post->user->fullName()}}</p>
                    {!! $post->content !!}
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        @hasSection('title')
            @yield('title') &mdash; blog
        @else
            blog
        @endif
    </title>
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}"/>
    @yield('styles')
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{{route('home')}}">blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                @auth
                    @if(auth()->user()->isPanelUser())
                        <li class="nav-item">
                            <a href="{{route('admin.dashboard')}}" class="nav-link">admin</a>
                        </li>
                    @endif
                @endauth
            </ul>
            <div class="my-2 my-lg-0">
                @auth
                    {{auth()->user()->fullName()}}
                    <a href="{{route('logout')}}">log out</a>
                @endauth
                @guest
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{{route('login')}}" class="nav-link">login</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{route('register')}}" class="nav-link">register</a>
                        </li>
                    </ul>
                @endguest
            </div>
        </div>
    </div>
</nav>
<div class="container mt-3 mb-3">
    @yield('content')
</div>
<script src="{{asset('js/jquery-3.5.1.min.js')}}"></script>
<script src="{{asset('js/bootstrap.bundle.min.js')}}"></script>
</body>
</html>

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>login &mdash; blog</title>
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/login.css')}}" rel="stylesheet">
</head>
<body class="text-center">

<form class="form-signin" action="{{route('login')}}" method="POST">
    @csrf
    <h1 class="h3 mb-3 font-weight-normal">
        <a href="{{route('home')}}">blog</a>
    </h1>
    @if(session('error'))
        <div class="alert alert-warning mb-3">
            {{session('error')}}
        </div>
    @endif
    <div class="form-group">
        <label for="inputEmail" class="sr-only">email</label>
        <input type="email" name="email" id="inputEmail" class="form-control" placeholder="email" required>
    </div>
    <div class="form-group">
        <label for="inputPassword" class="sr-only">password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="password" required>
    </div>
    <div class="form-group">
        <button class="btn btn-lg btn-primary btn-block" type="submit">login</button>
    </div>
    <div class="form-group">
        <a href="{{route('register')}}">register</a>
    </div>
</form>


</body>
</html>

resources/views/register.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>register &mdash; blog</title>
    <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{asset('css/register.css')}}" rel="stylesheet">
</head>
<body class="text-center">

<form class="form-signin" action="{{route('register')}}" method="POST">
    @csrf
    <h1 class="h3 mb-3 font-weight-normal">
        <a href="{{route('home')}}">blog</a>
    </h1>
    @if(session('error'))
        <div class="alert alert-warning mb-3">
            {{session('error')}}
        </div>
    @endif
    <div class="form-group">
        <label for="inputName" class="sr-only">name</label>
        <input type="text" name="name" id="inputName" class="form-control" placeholder="name" required>
    </div>
    <div class="form-group">
        <label for="inputSurname" class="sr-only">surname</label>
        <input type="text" name="surname" id="inputSurname" class="form-control" placeholder="surname" required>
    </div>
    <div class="form-group">
        <label for="inputEmail" class="sr-only">email</label>
        <input type="email" name="email" id="inputEmail" class="form-control" placeholder="email" required>
    </div>
    <div class="form-group">
        <label for="inputPassword" class="sr-only">password</label>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="password" required>
    </div>
    <div class="form-group">
        <button class="btn btn-lg btn-primary btn-block" type="submit">register</button>
    </div>
    <div class="form-group">
        <a href="{{route('login')}}">login</a>
    </div>
</form>


</body>
</html>